### ISSUE TITLE
Practica9

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-team-vo#1]
[PracticaFuncionalidades.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-team-vo/files/15266909/PracticaFuncionalidades.pdf)

**Comment by Aricel117** [comment]
Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
